version: '2'

services:
  elk:
    image: sebp/elk:latest
    ports:
      - 5601:5601
      - 9200:9200
      - 5044:5044
      - 5001:5000
    networks:
      - net
    volumes:
      - todo_elk:/var/lib/elasticsearch
    hostname: elk
    container_name: elk
    mem_limit: 4925288000  
    cpu_shares: 500  
    
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181
    networks:
      - net
    mem_limit: 925288000  
    cpu_shares: 100
  
  kafka:
    image: wurstmeister/kafka
    ports:
      - 9092
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 172.19.0.1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_CREATE_TOPICS: "todo-mail:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    hostname: kafka
    container_name: kafka
    networks:
      - net
    mem_limit: 925288000  
    cpu_shares: 100

volumes:
  todo_data:
    external: true
  todo_elk:
    external: true

networks:
  net:
    driver: bridge
